#!/bin/sh
rm ~/msf/temp/*.exe
rm ~/msf/temp/*.zip
rm ~/msf/temp/*.app
rm ~/msf/temp/*.apk
echo "All .exe, .zip, .app & .apk have been removed"
rm ~/msf/temp/.temp_ip_ngrok-tcp.txt
echo "temporary ngrok ip text removed"
rm ~/msf/temp/link-reverse*
echo "txt link file for payload uploading have been removedd"
